export const storefrontThemes = {
  classic: {
    id: 'classic',
    label: 'Classic Blue',
    brand: '#2563eb',
    brandStrong: '#1d4ed8',
    ink: '#1f2937',
    muted: '#6b7280',
    line: '#d1d5db',
    lineStrong: '#9ca3af',
    panel: '#ffffff',
    panelStrong: '#f9fafb',
    backdrop: '#f9fafb',
    heroBlend: '#ffffff',
    chip: '#eff6ff',
    danger: '#ef4444',
  },
  cobalt: {
    id: 'cobalt',
    label: 'Cobalt Commerce',
    brand: '#1d4ed8',
    brandStrong: '#1e40af',
    ink: '#1f2937',
    muted: '#6b7280',
    line: '#d1d5db',
    lineStrong: '#94a3b8',
    panel: '#ffffff',
    panelStrong: '#f8fafc',
    backdrop: '#f8fafc',
    heroBlend: '#ffffff',
    chip: '#dbeafe',
    danger: '#dc2626',
  },
  slate: {
    id: 'slate',
    label: 'Slate Blue',
    brand: '#3b82f6',
    brandStrong: '#2563eb',
    ink: '#111827',
    muted: '#6b7280',
    line: '#d1d5db',
    lineStrong: '#9ca3af',
    panel: '#ffffff',
    panelStrong: '#f3f4f6',
    backdrop: '#f9fafb',
    heroBlend: '#ffffff',
    chip: '#e5efff',
    danger: '#ef4444',
  },
}

export const defaultStorefrontTheme = storefrontThemes.classic

export function getStorefrontThemeVars(theme) {
  return {
    '--storefront-brand': theme.brand,
    '--storefront-brand-strong': theme.brandStrong,
    '--storefront-ink': theme.ink,
    '--storefront-muted': theme.muted,
    '--storefront-line': theme.line,
    '--storefront-panel': theme.panel,
    '--storefront-panel-strong': theme.panelStrong,
    '--storefront-backdrop': theme.backdrop,
    '--storefront-hero-blend': theme.heroBlend,
    '--storefront-chip': theme.chip,
    '--storefront-line-strong': theme.lineStrong,
    '--storefront-danger': theme.danger,
  }
}
